// All user-facing strings (Swedish). Keep code and identifiers in English.
import type { Frequency, GroupId, SessionShape } from './types';
import type { GroupState } from './engine/status';

export const APP_NAME = 'Digital PT';

export const GROUP_LABEL: Record<GroupId, string> = {
  vader: 'Vader',
  lar: 'Lår',
  rumpa: 'Rumpa',
  rygg: 'Rygg',
  mage: 'Mage',
  skuldror: 'Skuldror',
  axlar: 'Axlar',
  biceps: 'Biceps',
  triceps: 'Triceps',
  brost: 'Bröst',
  kardio: 'Kardio',
};

export const GROUP_ICON: Record<GroupId, string> = {
  vader: '🦵',
  lar: '🦿',
  rumpa: '🍑',
  rygg: '🔙',
  mage: '🎯',
  skuldror: '🧥',
  axlar: '🙌',
  biceps: '💪',
  triceps: '🦾',
  brost: '🫁',
  kardio: '❤️',
};

export const FREQUENCY_LABEL: Record<Frequency, string> = {
  ofta: 'Ofta',
  ibland: 'Ibland',
  sallan: 'Sällan',
};

export const TYPE_LABEL = { styrka: 'Styrka', kardio: 'Kardio' } as const;

export const SHAPE_LABEL: Record<SessionShape, string> = {
  fokus: 'Fokus',
  helkropp: 'Helkropp',
};

export const SHAPE_HELP: Record<SessionShape, string> = {
  fokus: 'Några muskelgrupper per pass',
  helkropp: 'Lite av allt som är utvilat',
};

export const STATE_LABEL: Record<GroupState, string> = {
  aldrig: 'aldrig tränad',
  vilar: 'vilar',
  redo: 'redo',
  'lange-sedan': 'länge sedan',
};

export const WEEKDAYS = ['måndag', 'tisdag', 'onsdag', 'torsdag', 'fredag', 'lördag', 'söndag'];
export const MONTHS = [
  'januari',
  'februari',
  'mars',
  'april',
  'maj',
  'juni',
  'juli',
  'augusti',
  'september',
  'oktober',
  'november',
  'december',
];

export const S = {
  tabs: { today: 'Idag', exercises: 'Övningar', history: 'Historik', settings: 'Inställningar' },

  install: {
    title: 'Lägg till på hemskärmen',
    intro: 'Digital PT fungerar bäst som en app på hemskärmen. Då sparas allt på telefonen och funkar även utan nät.',
    step1: 'Tryck på Dela-knappen i Safari',
    step2: 'Välj ”Lägg till på hemskärmen”',
    step3: 'Öppna appen från hemskärmen',
    notSafari: 'Öppna den här sidan i Safari för att kunna lägga till den på hemskärmen.',
    continueAnyway: 'Fortsätt i webbläsaren ändå',
  },

  update: {
    ready: 'En ny version är installerad.',
    reload: 'Starta om',
    offlineReady: 'Appen fungerar nu utan nät.',
  },

  common: {
    ok: 'OK',
    cancel: 'Avbryt',
    save: 'Spara',
    close: 'Stäng',
    back: 'Tillbaka',
    delete: 'Ta bort',
    edit: 'Ändra',
    add: 'Lägg till',
    search: 'Sök',
    done: 'Klar',
    skip: 'Hoppa över',
    next: 'Nästa',
    yes: 'Ja',
    no: 'Nej',
    loading: 'Laddar …',
    today: 'Idag',
    yesterday: 'Igår',
    daysAgo: (n: number) => (n === 1 ? '1 dag sedan' : `${n} dagar sedan`),
    never: 'aldrig',
    neverDone: 'Aldrig gjord',
    lastDone: 'Senast',
    exercisesCount: (n: number) => (n === 1 ? '1 övning' : `${n} övningar`),
    groupsCount: (n: number) => (n === 1 ? '1 grupp' : `${n} grupper`),
  },

  today: {
    noSession: 'Inget pass loggat idag.',
    suggest: 'Föreslå pass',
    suggestHelp: 'Appen väljer utvilade muskelgrupper',
    manual: 'Välj själv',
    manualHelp: 'Bocka av det du gör',
    progress: (done: number, total: number) => `${done} av ${total}`,
    allDone: 'Snyggt jobbat, allt klart!',
    addExercise: '+ Lägg till övning',
    hintsTitle: 'Länge sedan',
    hint: (group: string, days: number) => `${group}: ${days} dagar sedan`,
    hintNever: (group: string) => `${group}: aldrig tränad`,
    removeEntry: 'Ta bort från passet',
    emptySession: 'Passet är tomt. Lägg till en övning för att komma igång.',
    clearSession: 'Rensa dagens pass',
    clearSessionConfirm: 'Vill du ta bort alla övningar från dagens pass?',
    shortRestBadge: 'kort vila',
    exportNudge: 'Det var länge sedan du säkerhetskopierade.',
    exportNudgeAction: 'Säkerhetskopiera nu',
    exportNudgeNever: 'Du har inte säkerhetskopierat än.',
    missingExercise: 'Borttagen övning',
  },

  suggest: {
    title: 'Förslag på pass',
    start: 'Starta passet',
    newSuggestion: 'Nytt förslag',
    swap: 'Byt',
    remove: 'Ta bort',
    addAny: '+ Lägg till övning',
    groups: 'Muskelgrupper',
    count: 'Antal övningar',
    shape: 'Upplägg',
    cardio: 'Kardio',
    cardioOn: 'Med kardio',
    cardioOff: 'Utan kardio',
    reasonNever: 'aldrig tränad',
    reasonDays: (n: number) => (n === 1 ? '1 dag sedan' : `${n} dagar sedan`),
    reasonShortRest: (n: number) => `kort vila, ${n === 1 ? '1 dag' : `${n} dagar`}`,
    restingLabel: 'vilar',
    noExercises: 'Det finns inga övningar att föreslå. Lägg till övningar under Övningar först.',
    noSwap: 'Ingen annan övning att byta till.',
    empty: 'Inga övningar valda.',
  },

  manual: {
    title: 'Välj själv',
    help: 'Bocka för det du gör. Grupper som vilar är markerade.',
    resting: 'vilar',
    search: 'Sök övning',
    noMatches: 'Inga övningar matchar.',
    emptyLibrary: 'Du har inga övningar än. Lägg till från katalogen under Övningar.',
  },

  exercises: {
    title: 'Övningar',
    search: 'Sök i dina övningar',
    filterAll: 'Alla',
    newExercise: '+ Ny övning',
    empty: 'Inga övningar än.',
    emptyHelp: 'Lägg till övningar från katalogen så kan appen föreslå pass.',
    noMatches: 'Inga träffar.',
    archived: 'Arkiverade',
    archivedBadge: 'arkiverad',
    restore: 'Återställ',
    primary: 'Tränar främst',
    secondary: 'Tränar också',
    description: 'Beskrivning',
    youtube: 'Visa på YouTube',
    deleteConfirm: 'Ta bort övningen?',
    deleteArchivedNote: 'Den finns i din historik och arkiveras i stället, så historiken behålls.',
    deleteForever: 'Övningen tas bort helt.',
    fromCatalog: 'Från katalogen',
    own: 'Egen övning',
    inLibrary: 'finns redan',
    count: (n: number) => (n === 1 ? '1 övning' : `${n} övningar`),
  },

  add: {
    title: 'Lägg till övning',
    searchPlaceholder: 'Sök bland dina övningar och katalogen',
    browse: 'Bläddra i katalogen',
    create: 'Skapa egen',
    createTitle: 'Skapa egen övning',
    added: 'Tillagd',
    addToLibrary: 'Lägg till',
    addAndLog: 'Lägg till i passet',
    catalogTitle: 'Katalogen',
    chooseGroup: 'Välj muskelgrupp',
    name: 'Namn',
    namePlaceholder: 't.ex. Benpress i maskin',
    type: 'Typ',
    primaryGroups: 'Tränar främst (1–2)',
    secondaryGroups: 'Tränar också (valfritt)',
    note: 'Anteckning (valfritt)',
    notePlaceholder: 'Inställningar, vikt, tips …',
    nameRequired: 'Skriv ett namn.',
    nameTaken: 'Du har redan en övning med det namnet.',
    primaryRequired: 'Välj minst en muskelgrupp.',
    primaryMax: 'Högst två muskelgrupper.',
    noResults: 'Inga träffar. Du kan skapa en egen övning.',
    typeToSearch: 'Skriv för att söka, eller bläddra i katalogen.',
    inLibrary: 'finns redan',
    allInGroup: (group: string) => `Alla övningar för ${group.toLowerCase()}`,
    equipment: 'Utrustning',
  },

  history: {
    title: 'Historik',
    statusTitle: 'Muskelgrupper',
    sessionsTitle: 'Pass',
    empty: 'Inga pass än.',
    emptyHelp: 'Dina loggade pass visas här.',
    addPastSession: '+ Lägg till pass för ett tidigare datum',
    pickDate: 'Välj datum',
    editSession: 'Ändra pass',
    addToSession: '+ Lägg till övning',
    removeFromSession: 'Ta bort',
    deleteSession: 'Ta bort hela passet',
    deleteSessionConfirm: 'Ta bort passet och allt som loggats den dagen?',
    doneCount: (n: number) => (n === 1 ? '1 övning' : `${n} övningar`),
    plannedOnly: 'Inget avbockat',
    futureDate: 'Datumet kan inte vara i framtiden.',
    restingUntil: (n: number) => (n === 1 ? 'redo imorgon' : `redo om ${n} dagar`),
  },

  settings: {
    title: 'Inställningar',
    frequencyTitle: 'Hur ofta vill du träna varje muskelgrupp?',
    frequencyHelp: 'Styr hur appen prioriterar när den föreslår pass.',
    sessionTitle: 'Pass',
    exercisesPerSession: 'Övningar per pass',
    groupsPerSession: 'Muskelgrupper per pass',
    groupsPerSessionHelp: 'Gäller upplägget Fokus.',
    shape: 'Upplägg',
    restTitle: 'Vilodagar',
    restHelp: 'Så många dagar vilar en muskelgrupp efter ett pass.',
    restDays: (n: number) => (n === 1 ? '1 dag' : `${n} dagar`),
    resetDefaults: 'Återställ standardvärden',
    backupTitle: 'Säkerhetskopia',
    backupHelp: 'All data finns bara på den här telefonen. Spara en kopia då och då.',
    export: 'Exportera säkerhetskopia',
    import: 'Återställ från fil',
    importConfirmTitle: 'Återställ från säkerhetskopia?',
    importConfirm: 'Ersätter all data på den här telefonen.',
    importInvalid: 'Filen kunde inte läsas som en säkerhetskopia.',
    importDone: 'Återställt.',
    importSummary: (ex: number, sessions: number) => `${ex} övningar och ${sessions} pass i filen.`,
    lastExport: 'Senaste export',
    lastExportNever: 'Aldrig',
    exportFailed: 'Export misslyckades.',
    about: 'Om appen',
    aboutTitle: 'Om',
    version: 'Version',
    buildDate: 'Byggd',
    displayMode: 'Visningsläge',
    standalone: 'Hemskärm (standalone)',
    browser: 'Webbläsare',
    persisted: 'Lagring skyddad',
    persistedYes: 'Ja',
    persistedNo: 'Nej',
    persistedUnknown: 'Okänt',
    storage: 'Lagring',
    storageUsage: (used: string, quota: string) => `${used} av ${quota}`,
    errors: 'Senaste fel',
    noErrors: 'Inga fel har fångats.',
    copyDiagnostics: 'Kopiera diagnostik',
    copied: 'Kopierat',
    clearErrors: 'Rensa fel',
    counts: 'Innehåll',
    countsText: (ex: number, sessions: number) => `${ex} övningar, ${sessions} pass`,
    firstUse: 'Första användning',
    serviceWorker: 'Offline-stöd',
    swActive: 'Aktivt',
    swMissing: 'Saknas',
    onboardingAgain: 'Visa startguiden igen',
    catalogSize: 'Katalog',
    catalogEntries: (n: number) => `${n} övningar`,
  },

  onboarding: {
    welcome: 'Hej!',
    intro: 'Välj de övningar du brukar göra, så kan appen föreslå pass. Du kan alltid ändra senare.',
    start: 'Kom igång',
    skipAll: 'Hoppa över just nu',
    groupStep: (group: string) => `Vilka ${group.toLowerCase()}övningar gör du?`,
    groupStepKardio: 'Vilken kardio gör du?',
    selectedCount: (n: number) => (n === 1 ? '1 vald' : `${n} valda`),
    finish: 'Klar',
    doneTitle: 'Klart!',
    doneText: (n: number) => `${n} övningar ligger nu i ditt bibliotek. Lägg till fler under Övningar när du vill.`,
    goToToday: 'Till Idag',
    showMore: 'Visa fler',
  },

  format: {
    date: (weekday: string, day: number, month: string) => `${weekday} ${day} ${month}`,
    dateShort: (day: number, month: string) => `${day} ${month}`,
  },
} as const;
